### ISSUE TITLE
Поправить контекст

### ISSUE THREAD

**Issue by NikitaRzm** [Axent13/life#10]
Избавиться от ручного бинда контекстов посредством that и иже подобных вещей, где это возможно, посредством стрелочных функций.

**Comment by Znack** [comment]
Лучше вообще обработчики вынести в отдельные методы класса, когда ты создаешь в констукторе - у тебя на каждый инстанс контроллера будет создавать отдельный коллбэк - это нехорошо, учитывая, что можно использовать лишь одну копию этой функции, которая будет храниться в прототипе `Controller.prototype`

**Comment by Znack** [comment]
А получать доступ к элементу DOM-а на которй кликнули можно через `event.currentTarget` (кстати изучи отличие от `event.target`)
