### ISSUE TITLE
Добавить нормальные Unit тесты

### ISSUE THREAD

**Issue by Znack** [Axent13/life#13]
Сейчас модель у тебя проверяется в основном только как цельный модуль, который целиком сначала создает объект поля, потом изменяет его. Но мало проверок отдельных методов. Не оттестирован `changeCellState` например.

**Comment by Axent13** [comment]
Так оттестирован же -  
`describe('Checking changeCellState(cell)', () => {
        it('Dead cell should return alive', () => {
            const view = new View(1, 1);

```
        view.drawField();
        $('html').append("<td id=0-0 class='dead'></td>");
        const resultingClass = view.changeCellState($('td'));

        assert.equal(resultingClass, 'alive');
    });

    it('Alive cell should return dead', () => {
        const view = new View(1, 1);

        view.drawField();
        $('html').append("<td id=0-0 class='alive'></td>");
        const resultingClass = view.changeCellState($('td'));

        assert.equal(resultingClass, 'dead');
    });
});`
```

В самом конце файла test.js

**Comment by Znack** [comment]
Я про модель :) но кстати в модели тоже в тестах увидел. Но точно нет юнит тестов на конструктор :)
