### ISSUE TITLE
Добавить use-cases

### ISSUE THREAD

**Issue by Znack** [Axent13/life#14]
Сейчас много вариантов использования моделей не покрыты тестами. Например, у метода `_isElementInsideField` не проверяется, что будет, если передать параметрами -1, -1 (то есть вне поля, но по другой, минимальной, границе).
Вот тебе шутка в тему: http://pikabu.ru/story/testirovshchik_v_bare_3046939

**Comment by Znack** [comment]
А в интеграционных тестах твоего изменения состояния модели нет кстати проверки на случай, когда клетки на самой границе поля (то есть на позициях вроде 0,0) - тут надо отдельно затестить случай, что клетки не создаются на позиции -1, -1 например

**Comment by Axent13** [comment]
Ок, не вопрос, добавлю) просто подумал так сильно не париться с тестами в тестовом заданий)

**Comment by Znack** [comment]
Ну задание же на то, чтобы проверить понимание тобою TDD принципов в том числе, так что нелепо тут не париться соблюдать эти принципы :)
