### ISSUE TITLE
Привести к стандартам

### ISSUE THREAD

**Issue by Znack** [Axent13/life#27]
Очень много циклов for, очень много не вынесенных условий, отсупы должны быть 2 пробела, проверить остальные все правила из стандартов и исправить самому :)

**Comment by Znack** [comment]
Не все исправлено :) И по условиям не все вынес, и переменные названы одной буквой)
https://github.com/airbnb/javascript#naming--descriptive

**Comment by Axent13** [comment]
Про условия - я так понимаю, про этот метод:
``` _isElementInsideField(i, j) {
    if (j >= 0 && j < this._fieldHeight) {
      if (i >= 0 && i < this._fieldWidth) {
        return 1;
      }
    }
```
Где-то видел на stackoverflow предлагали сделать свой метод between типа такого:
```
Number.prototype.between(x, y, z){
  //тра-та-та
}
```
Можно так сделать? А то просто в стандартах указано "Не изменять прототипы стандартных конструкторов (String.prototype или Function.prototype), до тех пор пока вопрос внимательно не изучен и этот трюк не согласован со страшим разработчиком"?

**Comment by Znack** [comment]
В гитхабе надо тройные обратные кавычки просто использовать ``` ``` ``` :) 
Я там имел ввиду, что условия надо выносить в отдельные функции лучше иной раз. Тут у тебя вроде вынесено, это норм, но у тебя не везде так :)
