### ISSUE TITLE
Сложную верстку в js пихать не хорошо

### ISSUE THREAD

**Issue by Znack** [Axent13/life#28]
Функция по генерации разметки поля слишком усложнена, лучше воспользуйся шаблонизатором и легко уйдешь от ужасающих прибавлений строк, которые ты генерируешь с if-условиями к тому же. Боюсь представить, что начнется, если бизнес-логику усложнить (а в реальных проектах она постоянно усложняется и нельзя писать код только под текущие требования).

**Comment by Axent13** [comment]
Эмммм... а можно уточнить, что под "шаблонизатором" имеется ввиду?)))

**Comment by Znack** [comment]
Ну библиотеки типа ejs, pug, mustache.
