### ISSUE TITLE
За хранение состояния должна отвечать только модель, View не должна ничего хранить

### ISSUE THREAD

**Issue by Znack** [Axent13/life#31]
В этом, например, прелесть реакта, так как он позволяет сделать View как чистую функцию от Model, как, например, f(x) в математике говорит, что f зависит **только** от x, так и тут View = f(Model).
Это позволяет, в том числе сделать сильное разделение кода (то есть модель точно должна быть самодостаточной, а у тебя сейчас модель зависит от вью, так как она не понимает, идет игра сейчас или нет) и вью должна можно научить отображать другую модель, если у нее похожее API

**Comment by Axent13** [comment]
Хммм...а как тогда грамотно сообщить модели, что _"пользователь кликнул на клетку и она поменяла свое состояние"_? Это же во вью обрабатывается. У меня из-за этого как раз модель от вью и зависит:
`this._model.updateStates(this._view.getCellsStates());`
Я должен по идее при каждом клике на клетку сразу же модель менять, ведь так?

**Comment by Znack** [comment]
Модель и вью должны по минимуму друг от друга зависеть, для этого есть контроллер. Самый простой способ - вью сама от себя генерит события (смотри EventEmmiter), контроллер на них подписывается и дергает методы модели, получает новые данные и передает их во вью).

**Comment by Axent13** [comment]
Заюзал EventEmitter. Можешь проверить?)

**Comment by Znack** [comment]
> За хранение состояния должна отвечать только модель, View не должна ничего хранить #31
А ты в итоге из вью на контролер перенес хранение :)

**Comment by Axent13** [comment]
Так стоп. Хранение состояния чего? Состояния клеток?

**Comment by Znack** [comment]
Состояния игры :)

**Comment by Axent13** [comment]
А так?)

**Comment by Znack** [comment]
Ага, только добавь тесты :) Причем как в модель, так и для нового функционала контроллера

**Comment by Axent13** [comment]
Да да, про тесты я в курсе, потому и попросил поскорее проверить) А то задолбался уже переписывать тесты для каждого нового изменного API, который в итоге окажется не валидным)))
