### ISSUE TITLE
Проверка `it('should NOT begin game before controller is created'` не имеет смысла

### ISSUE THREAD

**Issue by Znack** [Axent13/life#32]
Она всегда будет проходить, тот момент что ты хотел проверить надо было по другому оформлять (импорт делать между замокиванием метода `initializeInterval` и проверкой его вызовов)

**Comment by Axent13** [comment]
Про импорт не понял - ты про такой импорт?
`import Controller from '../src/js/controller.js'`

**Comment by Znack** [comment]
Ага, про него :)

**Comment by Axent13** [comment]
В общем, после исправления других ишью у меня сам application.js поменялся и соответственно тест там теперь другой. Так что в этом ишью нужды больше нет, я думаю. Можно закрывать?

**Comment by Znack** [comment]
Ну давай)
