### ISSUE TITLE
`_changeCellListen` не проверяются аргументы, с которыми был вызван метод

### ISSUE THREAD

**Issue by Znack** [Axent13/life#42]

**Comment by Axent13** [comment]
Так вот же, в самом низу файла controller.js:
```
it('should call model.changeCellState() with parameters (0,0), after view emits changeCell', () => {
      const controller = new Controller();

      let spy = sinon.spy(Model.prototype, 'changeCellState');
      expect(spy.called).to.be.false;

      controller._view.emit('changeCell', '0-0');

      sinon.assert.calledWith(spy, '0', '0');
      spy.restore();
    });
```
Вот эта строчка: 
`sinon.assert.calledWith(spy, '0', '0');`
как раз и проверяет аргументы же.

**Comment by Znack** [comment]
Неприавильно копирнул название, там про `gameStateListen`
Шпион же должен быть вызван с тру или фолс?)

**Comment by Axent13** [comment]
Если ты точно про `gameStateListen`, то там же никаких аргументов у него нет, чтобы их проверять... или это я что-то не понимаю.)

**Comment by Axent13** [comment]
Ах да, сорян туплю) увидел аргументы, которые надо проверять)
