### ISSUE TITLE
Классы с префиксом js-

### ISSUE THREAD

**Issue by NikitaRzm** [Axent13/life#9]
Добавить на DOM-элементы классы с префиксом js, на которые вешаются обработчики, или с которыми работает JS-код. (js-start-button, js-stop-button и т.д) и заодно избавиться от id в верстке и в коде.

**Comment by Znack** [comment]
Это кстати не по стандартам - не использовать префикс и использовать id. Так что обязательно к исполнению и никогда не повторять в наших проектах.
